# Generated by Django 2.2 on 2020-01-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchaccounts',
            old_name='Invester',
            new_name='Investment',
        ),
    ]
