# Generated by Django 2.2 on 2020-01-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0004_auto_20200106_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchaccounts',
            name='Investment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='branchaccounts',
            name='Yearstart',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='branchaccounts',
            name='total_profit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='companybranches',
            name='branch_ConNo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employedetails',
            name='Yearofjoin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='emp_inproject',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='number_projects',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectincome',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='totalemp_branch',
            field=models.IntegerField(),
        ),
    ]
